# 検索したい楽天商品ジャンル・キーワード一覧
# `python scripts/search_rakuten.py --all` で全件まとめて検索されます
keywords:
  - "モンベル リュック"
  - "サロモン スニーカー"
  - "ザノースフェイス ポーチ"
  - "メッシュポーチ 韓国"
  - "ガチャガチャ コンプリート サンリオ"
  - "ジャーナルスタンダード バッグ"
  - "パタゴニア バッグ"
  - "アウトドア ウエストポーチ"
  - "韓国 ポーチ おしゃれ"
  - "スクイーズ ぬいぐるみ キーホルダー"
  - "mojojojo"
  - "ぬいぐるみキーホルダー 韓国"
  - "ガチャ 巾着ポーチ"
  - "ふわふわ フェイスポーチ"
  - "ポケットバッグ マルチポケット"
  - "グルミット ぬいぐるみ"
  - "ダイノテン"
